name: Upload firmware

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/build-firmware.yml
  release-firmware:
    runs-on: ubuntu-latest
    needs: call-build
    steps:

      - uses: actions/download-artifact@v3
        with:
          name: riotee_gateway_binary

      - run: mv zephyr.hex riotee_gateway_fw${{github.ref_name}}.hex

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: riotee_gateway_fw${{github.ref_name}}.hex